name: Update Homebrew Formula

on:
  repository_dispatch:
    types: [update-formula]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., v1.0.2)'
        required: true
        type: string

jobs:
  update-formula:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout homebrew-codx repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.HOMEBREW_UPDATE_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Update formula
      run: |
        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          VERSION="${{ github.event.client_payload.version }}"
        else
          VERSION="${{ github.event.inputs.version }}"
        fi
        python update_formula.py $VERSION
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Formula/codx.rb
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            VERSION="${{ github.event.client_payload.version }}"
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          git commit -m "Update formula to version $VERSION"
          git push
        fi